version: 1

name: domains-identity-visa-types-jg

pipelines:
  dev:
    phases:
    - type: github
      name: GitHub
      owner: byu-oit
      repo: domains-identity-visa-types-jg
      branch: master
    - type: codebuild
      name: Construction
      build_image: aws/codebuild/nodejs:6.3.1
    - type: handel
      name: Deployment
      environments_to_deploy:
      - dev
